### ISSUE TITLE
A question about 2x traning config

### ISSUE THREAD

**Issue by HB-X** [CityU-AIM-Group/HTD#2]
I found that htd_resnet101_2x.py is a multi-scale training config.
https://github.com/CityU-AIM-Group/HTD/blob/0be9fd844118c275abc6053b3cbd5ffb589e62ee/configs/htd/htd_resnet101_2x.py#L54.
So, I am not sure the well-trained model is strictly corresponding to this config.
https://portland-my.sharepoint.com/personal/wuyangli2-c_my_cityu_edu_hk/_layouts/15/onedrive.aspx?id=%2Fpersonal%2Fwuyangli2%2Dc%5Fmy%5Fcityu%5Fedu%5Fhk%2FDocuments%2F%E6%9C%AC%E5%9C%B0%E5%A4%87%E4%BB%BD%2Fmodels%2FTIP21%2DHTD&ga=1
Could you please check it again?

**Comment by wymanCV** [comment]
Hi, thank you for your attention.  

 I just checked my old training log and ensured the well-trained model was correctly trained with (1333, 800) single scale.  Thank you for finding the small mistake in the config file, and you can directly change them as follows (the screenshot is from my old log)

![image](https://user-images.githubusercontent.com/93365573/191804730-e16f8d0f-3a02-4c25-8765-78500729162b.png)

Since the names of some proposed modules were changed in our final-version paper, we modified the config files slightly to keep them consistent with our paper and didn't upload the raw config files. This leads to the mentioned small mistake.

**Comment by HB-X** [comment]
Thanks for your reply, I still have some confusion about this config. 
Why there are two types of bbox_roi_extractor (i.e., SingleRoIExtractor and AdptRoIExtractor) and box_head (i.e., Shared2FCBBoxHead and HTDBBoxHead) in this config? 
https://github.com/CityU-AIM-Group/HTD/blob/0be9fd844118c275abc6053b3cbd5ffb589e62ee/configs/htd/htd_resnet101_2x.py#L177
And why the assigner of rcnn contains different thresholds (0.5 and 0.6) ? 
https://github.com/CityU-AIM-Group/HTD/blob/0be9fd844118c275abc6053b3cbd5ffb589e62ee/configs/htd/htd_resnet101_2x.py#L256
Thank you.

**Comment by wymanCV** [comment]
Hi, thanks for your question. 

We follow the implementation of  [Reasoning RCNN](https://github.com/chanyn/Reasoning-RCNN/blob/master/configs/rrcnn/coco_reasoning_rcnn_r101_fpn_1x.py) to compare with the graph-related counterparts. Moreover, our method only modifies the second stage as [SGRN](https://openaccess.thecvf.com/content_CVPR_2019/papers/Xu_Spatial-Aware_Graph_Relation_Network_for_Large-Scale_Object_Detection_CVPR_2019_paper.pdf) after asking the authors of this paper.

**Comment by HB-X** [comment]
Thank you very much!
